### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Mr-Kips** [TheSpeedX/WhatScraper#11]
on (gui) there is:
**Traceback (most recent call last):
  File "whatscraper.py", line 289, in <module>
    main()
  File "whatscraper.py", line 144, in main
    from GUI import MainFrame
  File "/home/saqlain/Desktop/WhatScraper/GUI.py", line 10, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'**
while all the requirements are satisfied...

**Comment by TheSpeedX** [comment]
The GUI version requires an extra library `wxPython`
Try running
`pip3 install wxPython`
And run the tool.

**Comment by Mr-Kips** [comment]
Thank You sir , this was not mentioned there even in a Requirements.txt
Well , 2nd Question ?
May I use your code ?
I wanna build something like :
SQLite DB for link storage,
Search by Names
Inbuilt scrapping of Link Sharing websites
Storing links by search order and date
Even much more
Time by time...

**Comment by Mr-Kips** [comment]
Sir im a IT student currently in BS Software Engineering ,
Familiar with C , C++ , Java and somewhere python
even before i didn't contribute any thing to help people or as a Open
source .
This will be my 1st contribution to this world 🌎,
If you allows me I wanna use your that tool to go ahead in this race of
knowledge.
